### PR TITLE
Merge release/2.4 fixes into master

### PR DESCRIPTION
**Pull request by jcarpanelli**
I also added fixed some residual references to the deprecated `zosversion`. 

*Edit*: this PR should be merged and not squashed.

### CODE REVIEW

**Comment by ylv-io** [comment]
Why are we committing `examples/linking-contracts/build/`?

**Comment by jcarpanelli** [comment]
> Why are we committing examples/linking-contracts/build/ ?

Good question. Is there any reason behind this @spalladino? Or should I add it to the `.gitignore`?

**Comment by spalladino** [comment]
Good point. Not sure if the CI will work fine if we remove it though. If we remove it and it still works, I'm fine with it.

**Comment by jcarpanelli** [comment]
Seems to work fine! To master it goes then!

**Pull request merged**
